[package]
name = "ironduck-optimizer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ironduck-common.workspace = true
ironduck-planner.workspace = true
ironduck-catalog.workspace = true
hashbrown.workspace = true
thiserror.workspace = true
